version: '2.3'

services:
  clickhouse:
    image: ${CLICKHOUSE_SERVER_IMAGE}
    expose:
      - "9000"
      - "9009"
      - "8123"
      - "8443"
      - "9440"
      - "9181" # zookeeper port
    volumes:
        - ./configs/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
        - ./configs/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
        - ./configs/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    healthcheck:
        test: clickhouse client --query='select 1'
        interval: 3s
        timeout: 2s
        retries: 5
        start_period: 2s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_NICE
    security_opt:
      - label:disable
