version: '2.3'

services:
  zookeeper:
    image: zookeeper:3.4.12
    expose:
      - "2181"
    environment:
      ZOO_TICK_TIME: 500
      ZOO_MY_ID: 1
  #    ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s
    security_opt:
        - label:disable

  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse1
    environment:
      SHARD: 01
      REPLICA: 01
      CLUSTER: testcluster
    volumes:
      - ./_instances/clickhouse1/database/:/var/lib/clickhouse/
      - ./_instances/clickhouse1/logs/:/var/log/clickhouse-server/
    depends_on:
      zookeeper:
        condition: service_healthy

  clickhouse2:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse2
    environment:
      SHARD: 01
      REPLICA: 02
      CLUSTER: testcluster
    volumes:
      - ./_instances/clickhouse2/database/:/var/lib/clickhouse/
      - ./_instances/clickhouse2/logs/:/var/log/clickhouse-server/
    depends_on:
      zookeeper:
        condition: service_healthy

  clickhouse3:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse3
    environment:
      SHARD: 02
      REPLICA: 01
      CLUSTER: testcluster
    volumes:
      - ./_instances/clickhouse3/database/:/var/lib/clickhouse/
      - ./_instances/clickhouse3/logs/:/var/log/clickhouse-server/
    depends_on:
      zookeeper:
        condition: service_healthy

  clickhouse4:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse4
    environment:
      SHARD: 02
      REPLICA: 02
      CLUSTER: testcluster
    volumes:
      - ./_instances/clickhouse4/database/:/var/lib/clickhouse/
      - ./_instances/clickhouse4/logs/:/var/log/clickhouse-server/
    depends_on:
      zookeeper:
        condition: service_healthy

  # dummy service which do nothing, but allows to postpone 'docker-compose up -d' till all dependecies will go healthy
  all_services_ready:
    image: hello-world
    depends_on:
      clickhouse1:
        condition: service_healthy
      clickhouse2:
        condition: service_healthy
      clickhouse3:
        condition: service_healthy
      clickhouse4:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
